// Swap
export const SET_WEBSOCKET_STATUS = "SET_WEBSOCKET_STATUS";
export const SET_USER_DATA = "SET_USER_DATA";

export const GET_USER_DATA_FETCH_ACTION = "GET_USER_DATA_FETCH_ACTION";
export const GET_USER_DATA_LOADING_ACTION = "GET_USER_DATA_LOADING_ACTION";
export const GET_USER_DATA_SUCCESS = "GET_USER_DATA_SUCCESS";
export const GET_USER_DATA_FAILED = "GET_USER_DATA_FAILED";