// Swap
export const SET_WEBSOCKET_STATUS = "SET_WEBSOCKET_STATUS";
export const SET_USER_DATA = "SET_USER_DATA";

export const GET_USER_DATA_FETCH_ACTION = "GET_USER_DATA_FETCH_ACTION";
export const GET_USER_DATA_LOADING_ACTION = "GET_USER_DATA_LOADING_ACTION";
export const GET_USER_DATA_SUCCESS = "GET_USER_DATA_SUCCESS";
export const GET_USER_DATA_FAILED = "GET_USER_DATA_FAILED";


export const REQUEST_USER_NFT_ITEM = "REQUEST_USER_NFT_ITEM";
export const REQUEST_USER_NFT_ITEM_LOADING = "REQUEST_USER_NFT_ITEM_LOADING";
export const REQUEST_USER_NFT_ITEM_SUCCESS = "REQUEST_USER_NFT_ITEM_SUCCESS";
export const REQUEST_USER_NFT_ITEM_FAILED = "REQUEST_USER_NFT_ITEM_FAILED";

export const SET_CURRENT_NFT = "SET_CURRENT_NFT";
export const DELETE_CURRENT_NFT = "DELETE_CURRENT_NFT";

export const SET_CURRENT_TRADE = "SET_CURRENT_TRADE";
export const DELETE_CURRENT_TRADE = "DELETE_CURRENT_TRADE";


export const REQUEST_USER_TRADES = "REQUEST_USER_TRADES";
export const REQUEST_USER_TRADES_LOADING = "REQUEST_USER_TRADES_LOADING";
export const REQUEST_USER_TRADES_SUCCESS = "REQUEST_USER_TRADES_SUCCESS";
export const REQUEST_USER_TRADES_FAILED = "REQUEST_USER_TRADES_FAILED";

